### PR TITLE
Add Telegram Channel.

### PR DESCRIPTION
**Pull request by irazasyed**
Here's the new Telegram Channel.

It's not yet submitted to packagist ofc.

How do I maintain this BTW? PRs are not an easy way to manage this package (Have to wait for you guys to accept it?).

### CODE REVIEW

**Comment by alexsoft** [comment]
Hello!

I have a telegram channel too.
https://github.com/alexsoft/laravel-notifications-telegram

**Comment by irazasyed** [comment]
@alexsoft I see. Now, what? 

So we have 2 Telegram channels. Both end result is different and implementation as well  (Based on my quick review).

@themsaid @mpociot @freekmurze Please review and let us know what to do. 😄

**Comment by themsaid** [comment]
I think the best way is for you both to work on one package and make it 👌.

All authors in a package shall be mentioned in the README file, on the website we're preparing, as well as in composer.json

A shoutout on twitter will be given to everyone on v1.0 too.

**Comment by irazasyed** [comment]
Yeah, That's doable. But the question is, Who's joining whose package now?

My implementation looks like this:
Laravel Telegram Notification Example

It's an inline button and we can add as many buttons as we want [WIP - Adding Multi-Button Support Soon]. Whereas, @alexsoft's package sends an inline anchor link (No Button like in mine).

I prefer button over a simple link as it's consistent with other similar notification channels and it looks good too.

I don't know what @alexsoft wants to do in this case. I'm open for him to join as long as we have discussions prior to making any major changes (And mutual agreement on such changes ofc).

@themsaid BTW How does an author manage the packages? PRs seem to take quite a bit of time to review, accept, etc. from your end and in case there's a contribution by a third-party contributor, Other than only commenting, there's nothing an author can do. Perhaps, There should be a way to let the author maintain their package's lifecycle. What's the solution?

I wonder how thephpleague does it with so many authors (I see a lot of people in the org, Is that how its supposed to be?).

**Comment by themsaid** [comment]
I think every package author is part of the organisation there, with limited permissions per repository. I think that's how they manage it.

Will dig deeper into that in the next couple of hours until we sort it out :)

**Comment by themsaid** [comment]
@irazasyed you've been invited to the new repo for telegram :)

**Comment by irazasyed** [comment]
@themsaid Thanks. Just accepted it :)

**Pull request closed without merging**
