### PR TITLE
Pagerduty

### PR DESCRIPTION
**Pull request by lukewaite**

### CODE REVIEW

**Comment by freekmurze** [comment]
Hi, sorry for the wait. I've created a new repo called Pagerduty for you to work in.  You have write rights to that repo.

**Comment by lukewaite** [comment]
@freekmurze No apologies necessary! Thank you very much!

**Comment by lukewaite** [comment]
@freekmurze Any chance of getting admin on that repo? Need that for travis, etc..

image

**Comment by freekmurze** [comment]
Yup, let me take care of this real quick.

**Comment by lukewaite** [comment]
@freekmurze Sorry to ping you on this one again, but I think it is the last item at least...

I think whomever controls the packagist namespace will need to add the package, and then add me as a maintainer. 

image

Sorry, I can't be more explicit on this one as I'm not a member of any other packagist orgs/namespaces, so not entirely sure how that works....

**Comment by freekmurze** [comment]
No problem, on it!

**Comment by freekmurze** [comment]
https://packagist.org/packages/laravel-notification-channels/pagerduty

**Comment by lukewaite** [comment]
Thank you kindly!

**Pull request closed without merging**
